# Generated by Django 5.1.1 on 2024-10-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='client_contract',
            field=models.CharField(default='Test', max_length=50, verbose_name='Номер заявки клиенту'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='trans_contract',
            field=models.CharField(default='Test', max_length=50, verbose_name='Номер заявки перевозчику'),
            preserve_default=False,
        ),
    ]
