# Generated by Django 5.1.1 on 2024-10-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_client_contract_deal_trans_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='driver',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Контакт водителя'),
        ),
        migrations.AddField(
            model_name='deal',
            name='order_date',
            field=models.DateField(default='1990-01-01', verbose_name='Контакт водителя'),
            preserve_default=False,
        ),
    ]
