# Generated by Django 5.1.1 on 2024-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_deal_driver_deal_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='order_date',
            field=models.DateField(verbose_name='Дата заявки'),
        ),
    ]
