# Generated by Django 5.1.1 on 2024-10-08 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_our_company_rek_our_company_actual_address_and_more'),
        ('deals', '0004_alter_deal_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='client_our_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_our_company', to='clients.our_company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='client_text',
            field=models.CharField(default='Avrora', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='trans_our_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trans_our_company', to='clients.our_company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='trans_text',
            field=models.CharField(default='Avrora', max_length=100),
            preserve_default=False,
        ),
    ]
