# Generated by Django 5.1.1 on 2024-10-09 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_partner_name_alter_partner_tax_system_and_more'),
        ('deals', '0005_deal_client_our_company_deal_client_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='client_our_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_our_company', to='clients.our_company', verbose_name='Договор с клиентом от нас'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='trans_our_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_our_company', to='clients.our_company', verbose_name='Договор с перевозчиком от нас'),
        ),
    ]
