# Generated by Django 5.1.1 on 2024-10-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='add_costs',
            field=models.FloatField(max_length=7, verbose_name='Дополнительные затраты'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='income',
            field=models.FloatField(max_length=8, verbose_name='Доход'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='outcome',
            field=models.FloatField(max_length=8, verbose_name='Расход'),
        ),
    ]
