# Generated by Django 5.1.1 on 2024-10-04 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('client', 'Клиент'), ('trans', 'Перевозчик')], max_length=10)),
                ('tax_system', models.CharField(choices=[('general', 'Общая'), ('simp', 'Упрощенная')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rekvizity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=13, unique=True, verbose_name='ОГРН')),
                ('okpo', models.CharField(blank=True, max_length=10, null=True, verbose_name='ОКПО')),
                ('legal_address', models.CharField(max_length=255, verbose_name='Юридический адрес')),
                ('actual_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фактический адрес')),
                ('director', models.CharField(max_length=255, verbose_name='ФИО директора')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО контакта')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.partner', verbose_name='Контрагент')),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='rek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='clients.rekvizity'),
        ),
        migrations.CreateModel(
            name='Our_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_companies', to='clients.rekvizity')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Наименование банка')),
                ('bic', models.CharField(max_length=9, verbose_name='БИК')),
                ('correspondent_account', models.CharField(max_length=20, verbose_name='Корреспондентский счет')),
                ('checking_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('rekvizity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='clients.rekvizity', verbose_name='Реквизиты')),
            ],
        ),
    ]
