# Generated by Django 5.1.1 on 2024-10-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekvizity',
            name='company_full',
            field=models.CharField(blank=True, max_length=200, verbose_name='Полное название'),
        ),
        migrations.AddField(
            model_name='rekvizity',
            name='company_short',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сокращенное название'),
        ),
    ]
