# Generated by Django 5.1.1 on 2024-10-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rekvizity_company_full_rekvizity_company_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='rekvizity',
            name='ati_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
