# Generated by Django 5.1.1 on 2024-10-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rekvizity_ati_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='rek',
        ),
        migrations.AddField(
            model_name='rekvizity',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='clients.partner'),
            preserve_default=False,
        ),
    ]
