# Generated by Django 5.1.1 on 2024-10-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_partner_rek_rekvizity_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='position',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('director', 'Директор')], default='manager', max_length=50, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
