# Generated by Django 5.1.1 on 2024-10-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_contact_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_company',
            name='rek',
        ),
        migrations.AddField(
            model_name='our_company',
            name='actual_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='our_company',
            name='bank_name',
            field=models.CharField(default='def', max_length=255, verbose_name='Наименование банка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_company',
            name='bic',
            field=models.CharField(default=12, max_length=9, verbose_name='БИК'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_company',
            name='checking_account',
            field=models.CharField(default=123, max_length=20, verbose_name='Расчетный счет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_company',
            name='company_full',
            field=models.CharField(blank=True, max_length=200, verbose_name='Полное название'),
        ),
        migrations.AddField(
            model_name='our_company',
            name='company_short',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сокращенное название'),
        ),
        migrations.AddField(
            model_name='our_company',
            name='correspondent_account',
            field=models.CharField(default=123, max_length=20, verbose_name='Корреспондентский счет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_company',
            name='director',
            field=models.CharField(default='Alber', max_length=255, verbose_name='ФИО директора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_company',
            name='inn',
            field=models.CharField(default=123, max_length=12, unique=True, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_company',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='our_company',
            name='legal_address',
            field=models.CharField(default='aaa', max_length=255, verbose_name='Юридический адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_company',
            name='ogrn',
            field=models.CharField(default=123, max_length=13, unique=True, verbose_name='ОГРН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='our_company',
            name='okpo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='our_company',
            name='tax_system',
            field=models.CharField(choices=[('general', 'Общая'), ('simp', 'Упрощенная')], default='simp', max_length=100),
            preserve_default=False,
        ),
    ]
