# Generated by Django 5.1.1 on 2024-10-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_our_company_rek_our_company_actual_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Рабочее название'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='tax_system',
            field=models.CharField(choices=[('general', 'Общая'), ('simp', 'Упрощенная')], max_length=100, verbose_name='Налоговая система'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('client', 'Клиент'), ('trans', 'Перевозчик')], max_length=10, verbose_name='Тип контрагента'),
        ),
    ]
